---
env:
  - MIX_ENV=test
language: elixir
elixir:
  - 1.2.2
addons:
  postgresql: "9.4"
before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate
script: mix coveralls.travis
