---
env:
  - MIX_ENV=test

language: elixir

elixir:
  - 1.8

otp_release: "21.1"

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - cp config/travis.exs config/test.exs
  - mix ecto.create
  - mix ecto.migrate

script: mix coveralls.travis
